---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc
spec:
  storageClassName: mongo-vol
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
spec:
  storageClassName: mysql-vol
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  storageClassName: rabbitmq-vol
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi